export const ALL_ITEMS = [
  [
    { name: "Mighty Rosè", price: 11.5 },
    { name: "Mighty Mix", price: 10.0 },
    { name: "Mighty Oreo", price: 10.0 },
    { name: "Mighty Lotus", price: 10.0 },
    { name: "Mighty Special", price: 10.0 },
    { name: "Mighty Pistachio", price: 10.0 },
    { name: "Fruit Crepe", price: 9.5 },
    { name: "Sushi Crepe Plus", price: 10.5 },
    { name: "Sushi Banana", price: 10.5 },
    { name: "Oreo Fettuccine", price: 9.3 },
    { name: "Lotus Fettuccine", price: 9.3 },
    { name: "Fettuccine Crepe Plus", price: 10.5 },
    { name: "Rosè Crepe", price: 9.7 },
    { name: "Kinder Bueno Crepe", price: 8.5 },
    { name: "Raffaello Crepe", price: 8.5 },
    { name: "Diet Crepe", price: 8.0 },
  ],
  [
    { name: "Fruit Pancake", price: 9.5 },
    { name: "Pistachio Pancake", price: 9.5 },
    { name: "Lotus Pancake", price: 9.5 },
    { name: "Oreo Pancake", price: 9.5 },
    { name: "Caramel Pancake", price: 9.5 },
    { name: "Rosè Pancake", price: 9.5 },
  ],
  [
    { name: "American Mini", price: 9.5 },
    { name: "Mini Mix", price: 9.5 },
    { name: "Special Mini Pancake", price: 8.5 },
    { name: "Pistachio Mini Pancake", price: 8.5 },
    { name: "Oreo Mini Pancake", price: 8.5 },
    { name: "Lotus Mini Pancake", price: 8.5 },
    { name: "Rosè Pancake", price: 8.5 },
    { name: "Caramel Mini Pancake", price: 8.5 },
    { name: "Bueno Mini Pancake", price: 8.5 },
  ],
  [
    { name: "Diet Waffle", price: 8.0 },
    { name: "4 Blocks Waffle", price: 10.5 },
    { name: "Fruit Waffle", price: 9.5 },
    { name: "Pinky Waffle", price: 9.5 },
    { name: "Special Waffle", price: 10.0 },
    { name: "Oreo Waffle", price: 9.0 },
    { name: "Kinder Bueno Waffle", price: 9.0 },
    { name: "Gold Caramel Waffle", price: 9.0 },
    { name: "Raffaello Waffle", price: 9.0 },
    { name: "Pistachio Waffle", price: 9.0 },
    { name: "Lotus Waffle", price: 9.0 },
    { name: "Powder Sugar Waffle", price: 7.5 },
  ],
  [
    { name: "Avocado Fruit Salad", price: 11.0 },
    { name: "Nutella Fruit Salad", price: 10.0 },
    { name: "Vegan Fruit Salad", price: 8.5 },
    { name: "Emporio", price: 10.0 },
    { name: "Bomb", price: 10.0 },
  ],
  [
    { name: "Blu Beach", price: 6.5 },
    { name: "Sunrise", price: 6.5 },
    { name: "Strawberry Cooler", price: 6.5 },
    { name: "Red Moon", price: 6.5 },
    { name: "Pink Day", price: 6.5 },
    { name: "Dark Night", price: 6.5 },
  ],
  [
    { name: "Polo", price: 6.0 },
    { name: "Tropical Paradise", price: 6.0 },
    { name: "Kiwi Fresh", price: 6.0 },
    { name: "Kiwi Lemon Fresh", price: 6.0 },
    { name: "Strawberry Fresh", price: 6.0 },
    { name: "Strawberry Lemon Fresh", price: 6.0 },
    { name: "Granatapfel Fresh", price: 6.0 },
    { name: "Watermelon Fresh", price: 6.0 },
    { name: "Orange Fresh", price: 6.0 },
    { name: "Orange Lemon", price: 6.0 },
    { name: "Ananas Fresh", price: 6.0 },
    { name: "Ananas Lemon", price: 6.0 },
    { name: "Mango Fresh", price: 6.0 },
    { name: "Mix Rosè", price: 6.0 },
  ],
  [], // Ice items
  [
    { name: "Oreo Milkshake", price: 6.0 },
    { name: "Strawberries Milkshake", price: 6.0 },
    { name: "Kinder Bueno Milkshake", price: 6.0 },
    { name: "Lotus Milkshake", price: 6.0 },
    { name: "Pistachio Milkshake", price: 6.0 },
    { name: "Mango Milkshake", price: 6.0 },
    { name: "Caramel Milkshake", price: 6.0 },
    { name: "Chocolate Milkshake", price: 6.0 },
    { name: "Raffaello Milkshake", price: 6.0 },
    { name: "Ferrero Milkshake", price: 6.0 },
    { name: "Avocado Banana", price: 6.0 },
    { name: "Banana Milkshake", price: 6.0 },
  ],
  [
    { name: "Bubble Tea 0.5", price: 5.0 },
    { name: "Bubble Tea 0.7", price: 5.5 },
  ],
  [
    { name: "Bubble Milk 0.5", price: 5.5 },
    { name: "Bubble Milk 0.7", price: 6.0 },
  ],
  [
    { name: "Kaffee Cream", price: 2.5 },
    { name: "Cappuccino", price: 3.5 },
    { name: "Latte Macchiato", price: 3.6 },
    { name: "Caramel Macchiato (hot)", price: 4.0 },
    { name: "Caramel Macchiato (ice)", price: 5.0 },
    { name: "Vanilla Macchiato (hot)", price: 4.0 },
    { name: "Vanilla Macchiato (ice)", price: 5.0 },
    { name: "Haselnut Macchiato (hot)", price: 4.0 },
    { name: "Haselnut Macchiato (ice)", price: 5.0 },
    { name: "Amaretto Macchiato (hot)", price: 4.0 },
    { name: "Amaretto Macchiato (ice)", price: 5.0 },
    { name: "Espresso", price: 2.0 },
    { name: "Espresso Doppio", price: 2.8 },
    { name: "Cortado", price: 2.9 },
    { name: "Flat White", price: 3.5 },
    { name: "White Hot Chocolate", price: 4.0 },
    { name: "Milk Hot Chocolate", price: 4.0 },
    { name: "Dark Hot Chocolate", price: 4.0 },
  ],
  [{ name: "Chai Latte", price: 4.0 }],
  [
    { name: "Cola", price: 2.8 },
    { name: "Redbull", price: 3.5 },
    { name: "Fanta", price: 2.8 },
  ],
  [
    { name: "Schokolade", price: 1.0 },
    { name: "Obst", price: 2.0 },
    { name: "Sahne", price: 1.0 },

    { name: "Birthday Teller", price: 45.0 },
    { name: "Chocolate", price: 1.0 },
    { name: "Sahne", price: 1.0 },
    { name: "Kiwi", price: 0.5 },
    { name: "Strawberries", price: 0.5 },
    { name: "Hafer Milk", price: 0.5 },
    { name: "banana", price: 0.5 },
    { name: "Sirup", price: 0.5 },
    { name: "Kesha", price: 1.9 },
    { name: "Capri Sun", price: 1.0 },
    { name: "Cheesecakes", price: 6.0 },
    { name: "Ice", price: 2.0 },
    { name: "Tisch Reservieren", price: 25.0 },
    { name: "Wunderkerzen", price: 2.5 },
  ], // Cola/Redbull items;,
];
